import { parseCaseArtifact } from "@/domain/case/case-artifact";

export const tutorialCase = parseCaseArtifact({
  schemaVersion: 1,
  // 教程案件是真相账本的一次发布；内容变更必须升级版本，旧账本只服务历史存档。
  id: "case_rainy_study_v3",
  seed: "tutorial-rainy-study-v3",
  title: "雨夜书房",
  briefing:
    "暴雨夜，收藏家顾明远在自家举办了一场临时晚宴，几名与他关系紧张的客人都没有离开顾宅。晚宴临近结束时，二楼书房传来一声闷响；等众人赶到，顾明远已经倒在书桌旁。房门和窗户都没有遭到破坏，宅内的暴雨也切断了外出的可能。顾宅被暂时封闭，四名嫌疑人各自给出了一段看似完整的说法。",
  setting: {
    era: "contemporary",
    place: "临江市顾宅",
    occurredAt: "2026-08-30T21:10:00+08:00",
  },
  victimId: "character_gu_mingyuan",
  culpritId: "character_li_wenzhou",
  characters: [
    {
      id: "character_gu_mingyuan",
      name: "顾明远",
      roleTier: "victim",
      occupation: "艺术品收藏家",
      publicProfile: "顾宅主人，以严苛和多疑闻名。",
      privateProfile: "发现了李闻舟挪用基金会资金的证据，准备次日报警。",
      portraitTags: {
        gender: "male",
        ageGroup: "senior",
        temperament: ["严肃", "强势"],
      },
      knowledge: {
        factIds: ["fact_motive_embezzlement"],
        evidenceIds: ["evidence_transfer_ledger", "evidence_torn_audit_memo"],
        claimIds: [],
      },
      secretFactIds: ["fact_motive_embezzlement"],
      lieRules: [],
    },
    {
      id: "character_li_wenzhou",
      name: "李闻舟",
      roleTier: "suspect",
      occupation: "基金会财务主管",
      publicProfile: "替顾明远管理基金会账目，做事一向谨慎。",
      privateProfile:
        "挪用资金即将败露。他偷走门卡，在茶里加入镇静剂，随后用黄铜书挡杀害顾明远并伪造不在场证明。",
      portraitTags: {
        gender: "male",
        ageGroup: "middle",
        temperament: ["克制", "精明"],
      },
      knowledge: {
        factIds: [
          "fact_motive_embezzlement",
          "fact_method_sedative_bookend",
          "fact_opportunity_stolen_card",
          "fact_time_of_death",
        ],
        evidenceIds: [
          "evidence_transfer_ledger",
          "evidence_teacup_residue",
          "evidence_brass_bookend",
          "evidence_smart_lock_log",
        ],
        claimIds: ["claim_li_alibi"],
      },
      secretFactIds: [
        "fact_motive_embezzlement",
        "fact_method_sedative_bookend",
        "fact_opportunity_stolen_card",
      ],
      lieRules: [
        {
          factId: "fact_method_sedative_bookend",
          strategy: "deny",
          coverStatement: "我没有碰过顾先生的茶，也没有进入书房。",
        },
        {
          factId: "fact_opportunity_stolen_card",
          strategy: "fabricate_cover",
          coverStatement: "案发时我一直在客房和投资人通电话。",
        },
      ],
    },
    {
      id: "character_shen_lan",
      name: "沈岚",
      roleTier: "suspect",
      occupation: "油画修复师",
      publicProfile: "顾明远的女儿，近期因遗产安排与父亲发生争执。",
      privateProfile: "隐瞒了父女争吵，但案发时确实在远程修复室处理一幅油画。",
      portraitTags: {
        gender: "female",
        ageGroup: "young",
        temperament: ["敏感", "倔强"],
      },
      knowledge: {
        factIds: ["fact_relationship_shen", "fact_alibi_shen"],
        evidenceIds: ["evidence_paint_curing_record"],
        claimIds: ["claim_shen_alibi"],
      },
      secretFactIds: ["fact_relationship_shen"],
      lieRules: [
        {
          factId: "fact_relationship_shen",
          strategy: "minimize",
          coverStatement: "我们只是为一幅画意见不合，没有严重争吵。",
        },
      ],
    },
    {
      id: "character_zhao_heng",
      name: "赵衡",
      roleTier: "suspect",
      occupation: "前私人助理",
      publicProfile: "三天前被顾明远辞退，仍有部分私人物品留在顾宅。",
      privateProfile: "因违规出售藏品信息被辞退，但案发时正在一楼搬运寄存箱。",
      portraitTags: {
        gender: "male",
        ageGroup: "young",
        temperament: ["急躁", "防备"],
      },
      knowledge: {
        factIds: ["fact_context_zhao_fired", "fact_alibi_zhao"],
        evidenceIds: ["evidence_elevator_log"],
        claimIds: ["claim_zhao_alibi"],
      },
      secretFactIds: ["fact_context_zhao_fired"],
      lieRules: [
        {
          factId: "fact_context_zhao_fired",
          strategy: "deflect",
          coverStatement: "辞退只是工作分歧，与案子没有关系。",
        },
      ],
    },
    {
      id: "character_chen_mo",
      name: "陈默",
      roleTier: "suspect",
      occupation: "私人医生",
      publicProfile: "顾明远多年的医生和牌友，熟悉他的用药。",
      privateProfile: "曾给顾明远开过同类镇静剂，担心违规处方被发现，但没有参与犯罪。",
      portraitTags: {
        gender: "male",
        ageGroup: "middle",
        temperament: ["温和", "回避"],
      },
      knowledge: {
        factIds: ["fact_sedative_source", "fact_alibi_chen"],
        evidenceIds: ["evidence_teacup_residue", "evidence_livestream_record"],
        claimIds: ["claim_chen_alibi"],
      },
      secretFactIds: ["fact_sedative_source"],
      lieRules: [
        {
          factId: "fact_sedative_source",
          strategy: "minimize",
          coverStatement: "那只是常规短期处方，很多人都可能接触到。",
        },
      ],
    },
    {
      id: "character_luo_fang",
      name: "罗芳",
      roleTier: "witness",
      occupation: "顾宅管家",
      publicProfile: "在顾家工作十五年，熟悉宅内每个人的习惯。",
      privateProfile: "案发前看见李闻舟独自端走茶盘，但起初不敢指认雇主的财务主管。",
      portraitTags: {
        gender: "female",
        ageGroup: "middle",
        temperament: ["细心", "谨慎"],
      },
      knowledge: {
        factIds: ["fact_housekeeper_sighting", "fact_time_of_death"],
        evidenceIds: ["evidence_housekeeper_testimony"],
        claimIds: ["claim_luo_tea"],
      },
      secretFactIds: [],
      lieRules: [],
    },
    {
      id: "character_han_zhuo",
      name: "韩卓",
      roleTier: "witness",
      occupation: "安防系统工程师",
      publicProfile: "负责维护顾宅门禁、监控和电梯系统。",
      privateProfile: "能够恢复被删除的门禁记录，并确认日志没有系统故障。",
      portraitTags: {
        gender: "female",
        ageGroup: "young",
        temperament: ["理性", "直接"],
      },
      knowledge: {
        factIds: ["fact_opportunity_stolen_card", "fact_alibi_zhao"],
        evidenceIds: [
          "evidence_elevator_log",
          "evidence_smart_lock_log",
          "evidence_camera_reflection",
        ],
        claimIds: ["claim_han_logs"],
      },
      secretFactIds: [],
      lieRules: [],
    },
  ],
  scenes: [
    {
      id: "scene_study",
      name: "二楼书房",
      description:
        "顾明远倒在书桌旁，房门和窗户都没有暴力破坏痕迹。雨声压住了走廊动静，台灯仍亮着，书桌、书柜和茶杯都保持着案发后的原位。先固定物件位置、可见痕迹与可能的出入路径。",
      initiallyUnlocked: true,
      objects: [
        {
          id: "object_broken_watch",
          name: "破损腕表",
          description: "受害者腕表的表镜碎裂，指针停在九点十分。",
          actionAliases: ["检查腕表", "查看死亡时间"],
          evidenceIds: ["evidence_broken_watch"],
        },
        {
          id: "object_teacup",
          name: "半杯冷茶",
          description: "杯底残留少量浑浊沉淀。",
          actionAliases: ["检查茶杯", "化验茶水"],
          evidenceIds: ["evidence_teacup_residue"],
        },
        {
          id: "object_bookcase",
          name: "书柜与黄铜书挡",
          description: "一个黄铜书挡被放回书柜，表面有新近擦拭痕迹。",
          actionAliases: ["检查书柜", "检查黄铜书挡"],
          evidenceIds: ["evidence_brass_bookend"],
        },
        {
          id: "object_desk",
          name: "书桌",
          description: "抽屉没有上锁，碎纸篓中留有一角被撕毁的备忘录。",
          actionAliases: ["搜索书桌", "翻找抽屉", "检查碎纸篓"],
          evidenceIds: ["evidence_transfer_ledger", "evidence_torn_audit_memo"],
        },
      ],
    },
    {
      id: "scene_kitchen",
      name: "一楼厨房",
      description:
        "水壶仍有余温，茶盘少了一只杯子，台面残留刚被擦过的水痕。厨房是当晚茶水送往二楼的必经处，值守人员的去向与端茶经过值得逐一核实。",
      initiallyUnlocked: true,
      objects: [
        {
          id: "object_tea_tray",
          name: "茶盘",
          description: "管家记得案发前由李闻舟把茶盘端上楼。",
          actionAliases: ["检查茶盘", "询问谁端了茶"],
          evidenceIds: [],
        },
      ],
    },
    {
      id: "scene_security_room",
      name: "安防室",
      description:
        "门禁、监控与电梯记录都保存在一台离线终端中，屏幕上还停着一段异常的系统提示。这里能核验人员动线，但被删除的日志片段需要先取得进入权限并由懂系统的人协助恢复。",
      initiallyUnlocked: false,
      objects: [
        {
          id: "object_security_terminal",
          name: "安防终端",
          description: "需要韩卓恢复被删除的日志片段。",
          actionAliases: ["检查安防终端", "恢复门禁记录", "查看监控"],
          evidenceIds: [
            "evidence_elevator_log",
            "evidence_smart_lock_log",
            "evidence_camera_reflection",
          ],
        },
      ],
    },
  ],
  facts: [
    {
      id: "fact_motive_embezzlement",
      type: "motive",
      statement: "李闻舟挪用基金会资金，顾明远准备在次日报警。",
    },
    {
      id: "fact_method_sedative_bookend",
      type: "method",
      statement: "凶手先在茶中加入镇静剂，再使用黄铜书挡实施致命袭击。",
    },
    {
      id: "fact_opportunity_stolen_card",
      type: "opportunity",
      statement: "李闻舟使用顾明远遗失的备用门卡进入书房。",
    },
    {
      id: "fact_time_of_death",
      type: "context",
      statement: "死亡发生在二十一点十分前后。",
    },
    {
      id: "fact_alibi_shen",
      type: "alibi",
      statement: "沈岚在案发时持续操作远程修复室的恒温设备。",
    },
    {
      id: "fact_alibi_zhao",
      type: "alibi",
      statement: "赵衡在案发时间乘货梯往返一楼仓库，没有到过二楼。",
    },
    {
      id: "fact_alibi_chen",
      type: "alibi",
      statement: "陈默在案发时参加有多名观众见证的医学直播。",
    },
    {
      id: "fact_relationship_shen",
      type: "relationship",
      statement: "沈岚与父亲因遗产和藏品归属发生过激烈争吵。",
    },
    {
      id: "fact_context_zhao_fired",
      type: "context",
      statement: "赵衡因私自出售藏品信息被顾明远辞退。",
    },
    {
      id: "fact_sedative_source",
      type: "context",
      statement: "陈默曾为顾明远开具与茶中成分相同的镇静剂。",
    },
    {
      id: "fact_housekeeper_sighting",
      type: "opportunity",
      statement: "罗芳在案发前看见李闻舟独自把茶送往二楼。",
    },
  ],
  timeline: [
    {
      id: "event_prepare_tea",
      timestamp: "2026-08-30T20:38:00+08:00",
      sceneId: "scene_kitchen",
      characterIds: ["character_li_wenzhou", "character_luo_fang"],
      factIds: ["fact_housekeeper_sighting", "fact_method_sedative_bookend"],
      description: "李闻舟避开罗芳的视线，在茶中加入镇静剂后端走茶盘。",
    },
    {
      id: "event_enter_study",
      timestamp: "2026-08-30T21:06:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_li_wenzhou", "character_gu_mingyuan"],
      factIds: ["fact_opportunity_stolen_card"],
      description: "李闻舟使用备用门卡进入书房。",
    },
    {
      id: "event_murder",
      timestamp: "2026-08-30T21:10:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_li_wenzhou", "character_gu_mingyuan"],
      factIds: ["fact_method_sedative_bookend", "fact_time_of_death"],
      description: "药效发作后，李闻舟用黄铜书挡袭击顾明远。",
    },
    {
      id: "event_stage_scene",
      timestamp: "2026-08-30T21:16:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_li_wenzhou"],
      factIds: ["fact_opportunity_stolen_card"],
      description: "李闻舟擦拭书挡并删除部分门禁日志，试图制造密室假象。",
    },
    {
      id: "event_body_found",
      timestamp: "2026-08-30T21:32:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_luo_fang", "character_gu_mingyuan"],
      factIds: ["fact_time_of_death"],
      description: "罗芳送水时发现顾明远倒在书桌旁。",
    },
  ],
  claims: [
    {
      id: "claim_li_alibi",
      speakerId: "character_li_wenzhou",
      kind: "lie",
      statement: "九点前后我一直在客房打电话，从未上过二楼。",
      factIds: ["fact_opportunity_stolen_card", "fact_method_sedative_bookend"],
    },
    {
      id: "claim_shen_alibi",
      speakerId: "character_shen_lan",
      kind: "truth",
      statement: "我在远程修复室处理油画，恒温设备记录可以证明。",
      factIds: ["fact_alibi_shen"],
    },
    {
      id: "claim_zhao_alibi",
      speakerId: "character_zhao_heng",
      kind: "truth",
      statement: "我一直在一楼搬箱子，货梯记录会留下时间。",
      factIds: ["fact_alibi_zhao"],
    },
    {
      id: "claim_chen_alibi",
      speakerId: "character_chen_mo",
      kind: "truth",
      statement: "我当时正在进行医学直播，观众和平台记录都能作证。",
      factIds: ["fact_alibi_chen"],
    },
    {
      id: "claim_luo_tea",
      speakerId: "character_luo_fang",
      kind: "truth",
      statement: "我看见李闻舟说要替我送茶，然后一个人端着茶盘上楼。",
      factIds: ["fact_housekeeper_sighting"],
    },
    {
      id: "claim_han_logs",
      speakerId: "character_han_zhuo",
      kind: "truth",
      statement: "门禁记录被人为删除过，但底层备份可以恢复。",
      factIds: ["fact_opportunity_stolen_card", "fact_alibi_zhao"],
    },
  ],
  evidence: [
    {
      id: "evidence_broken_watch",
      name: "停在九点十分的腕表",
      description: "破损表镜和尸体状况共同限定了死亡时间。",
      kind: "physical",
      supportsFactIds: ["fact_time_of_death"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: [],
      critical: false,
      discovery: {
        method: "inspect",
        sceneId: "scene_study",
        objectId: "object_broken_watch",
        actionAliases: ["检查腕表", "查看表盘"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_teacup_residue",
      name: "茶杯中的镇静剂残留",
      description: "化验发现茶中含有足以造成明显迟钝的镇静剂。",
      kind: "forensic",
      supportsFactIds: ["fact_method_sedative_bookend", "fact_sedative_source"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "analyze",
        sceneId: "scene_study",
        objectId: "object_teacup",
        actionAliases: ["化验茶水", "检查杯底沉淀"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_brass_bookend",
      name: "被擦拭的黄铜书挡",
      description: "缝隙中残留受害者的皮屑和李闻舟西装袖口的纤维。",
      kind: "forensic",
      supportsFactIds: ["fact_method_sedative_bookend"],
      contradictsClaimIds: ["claim_li_alibi"],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: false,
      discovery: {
        method: "inspect",
        sceneId: "scene_study",
        objectId: "object_bookcase",
        actionAliases: ["检查黄铜书挡", "寻找擦拭痕迹"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_transfer_ledger",
      name: "异常转账账簿",
      description: "多笔资金最终流入李闻舟控制的空壳账户。",
      kind: "document",
      supportsFactIds: ["fact_motive_embezzlement"],
      contradictsClaimIds: [],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "search",
        sceneId: "scene_study",
        objectId: "object_desk",
        actionAliases: ["翻找书桌抽屉", "检查账簿"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_torn_audit_memo",
      name: "被撕毁的审计备忘录",
      description: "备忘录写明顾明远将在次日上午提交财务证据。",
      kind: "document",
      supportsFactIds: ["fact_motive_embezzlement"],
      contradictsClaimIds: [],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "inspect",
        sceneId: "scene_study",
        objectId: "object_desk",
        actionAliases: ["检查碎纸篓", "拼合备忘录"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_paint_curing_record",
      name: "修复室恒温记录",
      description: "沈岚在案发前后持续调整设备，操作带有本人双重认证。",
      kind: "digital",
      supportsFactIds: ["fact_alibi_shen"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: ["character_shen_lan"],
      critical: true,
      discovery: {
        method: "query",
        actionAliases: ["查询修复室记录", "核实沈岚的不在场证明"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_elevator_log",
      name: "货梯运行日志",
      description: "赵衡的门卡在案发时间只操作过一楼与地下仓库。",
      kind: "digital",
      supportsFactIds: ["fact_alibi_zhao"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: ["character_zhao_heng"],
      critical: true,
      discovery: {
        method: "query",
        sceneId: "scene_security_room",
        objectId: "object_security_terminal",
        actionAliases: ["查询货梯日志", "核实赵衡的门卡"],
        prerequisiteEvidenceIds: ["evidence_torn_audit_memo"],
      },
    },
    {
      id: "evidence_livestream_record",
      name: "陈默提供的直播回放链接",
      description: "陈默在追问下提供了平台后台回放链接，连续画面和观众互动证明他案发时身处城南诊所。",
      kind: "digital",
      supportsFactIds: ["fact_alibi_chen"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: ["character_chen_mo"],
      critical: true,
      discovery: {
        method: "interview",
        characterId: "character_chen_mo",
        actionAliases: ["询问陈默案发时在哪里", "追问医学直播", "核实陈默的不在场证明"],
        dialogueAliases: [
          "案发时你在哪里",
          "你当晚一直在诊所吗",
          "医学直播能证明你的不在场吗",
        ],
        dialogueUtterance:
          "我当晚一直在城南诊所直播，可以提供平台后台的回放链接和观众互动记录。",
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_smart_lock_log",
      name: "恢复的书房门禁日志",
      description: "九点零六分，顾明远遗失的备用门卡打开了书房。",
      kind: "digital",
      supportsFactIds: ["fact_opportunity_stolen_card"],
      contradictsClaimIds: ["claim_li_alibi"],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "analyze",
        sceneId: "scene_security_room",
        objectId: "object_security_terminal",
        actionAliases: ["恢复门禁日志", "检查备用门卡记录"],
        prerequisiteEvidenceIds: ["evidence_torn_audit_memo"],
      },
    },
    {
      id: "evidence_camera_reflection",
      name: "监控玻璃中的倒影",
      description: "被删除画面的边缘倒影显示李闻舟在九点零五分走上二楼。",
      kind: "digital",
      supportsFactIds: ["fact_opportunity_stolen_card"],
      contradictsClaimIds: ["claim_li_alibi"],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "analyze",
        sceneId: "scene_security_room",
        objectId: "object_security_terminal",
        actionAliases: ["逐帧查看监控", "放大玻璃倒影"],
        prerequisiteEvidenceIds: ["evidence_smart_lock_log"],
      },
    },
    {
      id: "evidence_housekeeper_testimony",
      name: "罗芳关于茶盘的证词",
      description: "罗芳确认是李闻舟主动提出替她送茶，并独自前往二楼。",
      kind: "testimony",
      supportsFactIds: ["fact_housekeeper_sighting"],
      contradictsClaimIds: ["claim_li_alibi"],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "interview",
        characterId: "character_luo_fang",
        actionAliases: ["询问罗芳谁送了茶", "追问茶盘经过"],
        dialogueAliases: [
          "谁把茶送进书房",
          "茶盘后来是谁拿走的",
          "你看到谁去二楼了吗",
        ],
        dialogueUtterance:
          "我看到李闻舟主动接过茶盘，说由他送上楼，之后独自去了二楼。",
        prerequisiteEvidenceIds: [],
      },
    },
  ],
  unlockRules: [
    {
      id: "unlock_security_room",
      targetType: "scene",
      targetId: "scene_security_room",
      allEvidenceIds: ["evidence_torn_audit_memo"],
      anyEvidenceIds: [],
    },
    {
      id: "unlock_han_zhuo",
      targetType: "character",
      targetId: "character_han_zhuo",
      allEvidenceIds: ["evidence_torn_audit_memo"],
      anyEvidenceIds: [],
    },
  ],
  hintChains: [
    {
      id: "hint_motive",
      targetFactId: "fact_motive_embezzlement",
      hints: [
        "顾明远最近似乎准备采取一项正式行动。",
        "书桌附近可能留有与财务有关的材料。",
        "检查抽屉账簿和碎纸篓中的审计备忘录。",
      ],
    },
    {
      id: "hint_method",
      targetFactId: "fact_method_sedative_bookend",
      hints: [
        "受害者遇袭前的状态可能并不正常。",
        "茶杯和被擦拭过的摆件值得分别检查。",
        "化验冷茶，并检查书柜上的黄铜书挡。",
      ],
    },
    {
      id: "hint_opportunity",
      targetFactId: "fact_opportunity_stolen_card",
      hints: [
        "没有破门痕迹，不等于没人开过门。",
        "审计备忘录会引出一个新的调查地点。",
        "找到备忘录后前往安防室恢复门禁和监控记录。",
      ],
    },
  ],
  solution: {
    culpritId: "character_li_wenzhou",
    motiveFactId: "fact_motive_embezzlement",
    methodFactId: "fact_method_sedative_bookend",
    requiredEvidenceIds: [
      "evidence_teacup_residue",
      "evidence_brass_bookend",
      "evidence_transfer_ledger",
      "evidence_paint_curing_record",
      "evidence_elevator_log",
      "evidence_livestream_record",
      "evidence_smart_lock_log",
      "evidence_housekeeper_testimony",
    ],
    requiredTimelineEventIds: [
      "event_prepare_tea",
      "event_enter_study",
      "event_murder",
    ],
  },
});
