import { parseCaseArtifact } from "@/domain/case/case-artifact";

export const tutorialCase = parseCaseArtifact({
  schemaVersion: 1,
  // 教程案件是真相账本的一次发布；内容变更必须升级版本，旧账本只服务历史存档。
  id: "case_rainy_study_v5",
  seed: "tutorial-rainy-study-v5",
  title: "雨夜书房",
  briefing:
    "暴雨夜，收藏家顾明远在自家举办了一场临时晚宴。散席后，管家再次上楼时发现他倒在二楼书桌旁。房门和窗户都没有遭到破坏，腕表虽然停了，死亡时间仍需核实。顾宅被暂时封闭，当晚与顾明远有接触的四名嫌疑人各自给出了一段看似完整的说法。",
  setting: {
    era: "contemporary",
    place: "临江市顾宅",
    occurredAt: "2026-08-30T21:10:00+08:00",
  },
  victimId: "character_gu_mingyuan",
  culpritId: "character_li_wenzhou",
  characters: [
    {
      id: "character_gu_mingyuan",
      name: "顾明远",
      roleTier: "victim",
      occupation: "艺术品收藏家",
      publicProfile: "顾宅主人，以严苛和多疑闻名。",
      privateProfile: "发现了李闻舟挪用基金会资金的证据，准备次日报警。",
      portraitTags: {
        gender: "male",
        ageGroup: "senior",
        temperament: ["严肃", "强势"],
      },
      knowledge: {
        factIds: ["fact_motive_embezzlement"],
        evidenceIds: ["evidence_transfer_ledger", "evidence_torn_audit_memo"],
        claimIds: [],
      },
      secretFactIds: ["fact_motive_embezzlement"],
      lieRules: [],
    },
    {
      id: "character_li_wenzhou",
      name: "李闻舟",
      roleTier: "suspect",
      occupation: "基金会财务主管",
      publicProfile: "替顾明远管理基金会账目，做事一向谨慎。",
      privateProfile:
        "挪用资金即将败露。他偷走门卡，在茶里加入镇静剂，随后用黄铜书挡杀害顾明远并伪造不在场证明。",
      portraitTags: {
        gender: "male",
        ageGroup: "middle",
        temperament: ["克制", "精明"],
      },
      knowledge: {
        factIds: [
          "fact_motive_embezzlement",
          "fact_method_sedative_bookend",
          "fact_opportunity_stolen_card",
          "fact_time_of_death",
        ],
        evidenceIds: [
          "evidence_transfer_ledger",
          "evidence_teacup_residue",
          "evidence_brass_bookend",
          "evidence_smart_lock_log",
        ],
        claimIds: ["claim_li_alibi"],
      },
      secretFactIds: [
        "fact_motive_embezzlement",
        "fact_method_sedative_bookend",
        "fact_opportunity_stolen_card",
      ],
      lieRules: [
        {
          factId: "fact_method_sedative_bookend",
          strategy: "deny",
          coverStatement: "我没有碰过顾先生的茶，也没有进入书房。",
        },
        {
          factId: "fact_opportunity_stolen_card",
          strategy: "fabricate_cover",
          coverStatement: "案发时我一直在客房和投资人通电话。",
        },
      ],
    },
    {
      id: "character_shen_lan",
      name: "沈岚",
      roleTier: "suspect",
      occupation: "油画修复师",
      publicProfile: "顾明远的女儿，从事油画修复，当晚在顾宅参加晚宴。",
      privateProfile: "隐瞒了父女争吵，但二十点三十分至二十一点三十五分确实一直在顾宅西侧附楼的修复室处理油画。",
      portraitTags: {
        gender: "female",
        ageGroup: "young",
        temperament: ["敏感", "倔强"],
      },
      knowledge: {
        factIds: ["fact_relationship_shen", "fact_alibi_shen"],
        evidenceIds: ["evidence_paint_curing_record"],
        claimIds: ["claim_shen_alibi"],
      },
      secretFactIds: ["fact_relationship_shen"],
      lieRules: [
        {
          factId: "fact_relationship_shen",
          strategy: "minimize",
          coverStatement: "我们只是为一幅画意见不合，没有严重争吵。",
        },
      ],
    },
    {
      id: "character_zhao_heng",
      name: "赵衡",
      roleTier: "suspect",
      occupation: "前私人助理",
      publicProfile: "曾协助顾明远管理日程，当晚来顾宅整理寄存物品。",
      privateProfile: "因违规出售藏品信息被辞退，但二十点三十分至二十一点三十五分一直在一楼装卸区、货梯与地下仓库之间搬运寄存箱。",
      portraitTags: {
        gender: "male",
        ageGroup: "young",
        temperament: ["急躁", "防备"],
      },
      knowledge: {
        factIds: ["fact_context_zhao_fired", "fact_alibi_zhao"],
        evidenceIds: ["evidence_elevator_log"],
        claimIds: ["claim_zhao_alibi"],
      },
      secretFactIds: ["fact_context_zhao_fired"],
      lieRules: [
        {
          factId: "fact_context_zhao_fired",
          strategy: "deflect",
          coverStatement: "辞退只是工作分歧，与案子没有关系。",
        },
      ],
    },
    {
      id: "character_chen_mo",
      name: "陈默",
      roleTier: "suspect",
      occupation: "私人医生",
      publicProfile: "顾明远多年的医生和牌友，熟悉他的用药。当晚来顾宅短暂赴宴后返回城南诊所。",
      privateProfile: "曾给顾明远开过同类镇静剂，担心违规处方被发现，但没有参与犯罪。",
      portraitTags: {
        gender: "male",
        ageGroup: "middle",
        temperament: ["温和", "回避"],
      },
      knowledge: {
        factIds: ["fact_sedative_source", "fact_alibi_chen"],
        evidenceIds: ["evidence_teacup_residue", "evidence_livestream_record"],
        claimIds: ["claim_chen_alibi"],
      },
      secretFactIds: ["fact_sedative_source"],
      lieRules: [
        {
          factId: "fact_sedative_source",
          strategy: "minimize",
          coverStatement: "那只是常规短期处方，很多人都可能接触到。",
        },
      ],
    },
    {
      id: "character_luo_fang",
      name: "罗芳",
      roleTier: "witness",
      occupation: "顾宅管家",
      publicProfile: "在顾家工作十五年，熟悉宅内每个人的习惯。",
      privateProfile: "案发前洗杯沏茶，看见李闻舟独自端走茶盘，随后看见顾明远接杯喝茶，但没有看见投药。起初不敢指认雇主的财务主管。",
      portraitTags: {
        gender: "female",
        ageGroup: "middle",
        temperament: ["细心", "谨慎"],
      },
      knowledge: {
        factIds: ["fact_housekeeper_sighting", "fact_time_of_death"],
        evidenceIds: ["evidence_housekeeper_testimony"],
        claimIds: ["claim_luo_tea"],
      },
      secretFactIds: [],
      lieRules: [],
    },
    {
      id: "character_han_zhuo",
      name: "韩卓",
      roleTier: "witness",
      occupation: "安防系统工程师",
      publicProfile: "负责维护顾宅门禁、监控和电梯系统。",
      privateProfile: "能够恢复被删除的门禁记录，并确认日志没有系统故障。",
      portraitTags: {
        gender: "female",
        ageGroup: "young",
        temperament: ["理性", "直接"],
      },
      knowledge: {
        factIds: ["fact_deleted_security_log"],
        evidenceIds: [],
        claimIds: ["claim_han_logs"],
      },
      secretFactIds: [],
      lieRules: [],
    },
  ],
  scenes: [
    {
      id: "scene_study",
      name: "二楼书房",
      description:
        "顾明远倒在书桌旁，房门和窗户都没有暴力破坏痕迹。雨声压住了走廊动静，台灯仍亮着，书桌、书柜和茶杯都保持着案发后的原位。先固定物件位置、可见痕迹与可能的出入路径。",
      initiallyUnlocked: true,
      objects: [
        {
          id: "object_broken_watch",
          name: "破损腕表",
          description: "受害者腕表的表镜碎裂，指针停在九点十分。对应物证袋附有现场时间勘验记录，可核对停表是否等于死亡时间。",
          actionAliases: ["检查腕表", "查看死亡时间"],
          evidenceIds: ["evidence_broken_watch"],
        },
        {
          id: "object_teacup",
          name: "半杯冷茶",
          description: "杯底残留少量浑浊沉淀。",
          actionAliases: ["检查茶杯", "化验茶水"],
          evidenceIds: ["evidence_teacup_residue"],
        },
        {
          id: "object_bookcase",
          name: "书柜与黄铜书挡",
          description: "一个黄铜书挡被放回书柜，表面有新近擦拭痕迹。",
          actionAliases: ["检查书柜", "检查黄铜书挡"],
          evidenceIds: ["evidence_brass_bookend"],
        },
        {
          id: "object_desk",
          name: "书桌",
          description: "抽屉没有上锁，碎纸篓中留有一角被撕毁的备忘录。",
          actionAliases: ["搜索书桌", "翻找抽屉", "检查碎纸篓"],
          evidenceIds: ["evidence_transfer_ledger", "evidence_torn_audit_memo"],
        },
      ],
    },
    {
      id: "scene_kitchen",
      name: "一楼厨房",
      description:
        "水壶仍有余温，茶盘少了一只杯子，台面残留刚被擦过的水痕。厨房是当晚茶水送往二楼的必经处，值守人员的去向与端茶经过值得逐一核实。",
      initiallyUnlocked: true,
      objects: [
        {
          id: "object_tea_tray",
          name: "茶盘",
          description: "茶盘上留有杯底水印，洗杯、沏茶与送茶经过需要向管家核实。",
          actionAliases: ["检查茶盘", "询问谁端了茶"],
          evidenceIds: [],
        },
      ],
    },
    {
      id: "scene_security_room",
      name: "安防室",
      description:
        "门禁、监控与电梯记录都保存在一台离线终端中，屏幕上还停着一段异常的系统提示。这里能核验人员动线，但被删除的日志片段需要先取得进入权限并由懂系统的人协助恢复。",
      initiallyUnlocked: false,
      objects: [
        {
          id: "object_security_terminal",
          name: "安防终端",
          description: "需要韩卓恢复被删除的日志片段。",
          actionAliases: ["检查安防终端", "恢复门禁记录", "查看监控"],
          evidenceIds: [
            "evidence_elevator_log",
            "evidence_smart_lock_log",
            "evidence_camera_reflection",
          ],
        },
      ],
    },
  ],
  facts: [
    {
      id: "fact_motive_embezzlement",
      type: "motive",
      statement: "李闻舟挪用基金会资金，顾明远准备在次日报警。",
    },
    {
      id: "fact_fund_diversion",
      type: "context",
      statement: "基金会多笔未经授权的转账流入李闻舟控制的空壳账户。",
    },
    {
      id: "fact_method_sedative_bookend",
      type: "method",
      statement: "凶手先在茶中加入镇静剂，再使用黄铜书挡实施致命袭击。",
    },
    {
      id: "fact_sedative_in_tea",
      type: "context",
      statement: "顾明远生前饮下含镇静剂的茶，剂量足以造成迟钝但不致死；可投放时段从二十点三十五分洗杯配茶起至致命袭击前。",
    },
    {
      id: "fact_opportunity_stolen_card",
      type: "opportunity",
      statement: "李闻舟使用顾明远遗失的备用门卡进入书房。",
    },
    {
      id: "fact_spare_card_entry",
      type: "context",
      statement: "顾明远报失的备用门卡在二十一点零六分打开书房，门禁日志本身不记录持卡人的身份。",
    },
    {
      id: "fact_deleted_security_log",
      type: "context",
      statement: "书房门禁记录曾被人为删除，离线终端保留了可恢复的底层备份。",
    },
    {
      id: "fact_time_of_death",
      type: "context",
      statement: "致命袭击发生在二十点三十五分确认顾明远存活之后、二十一点三十二分发现尸体之前；九点十分的停表只能作为佐证。",
    },
    {
      id: "fact_alibi_shen",
      type: "alibi",
      statement: "二十点三十分至二十一点三十五分，沈岚本人连续身处顾宅西侧附楼修复室。",
    },
    {
      id: "fact_alibi_zhao",
      type: "alibi",
      statement: "二十点三十分至二十一点三十五分，赵衡本人连续在一楼装卸区、货梯与地下仓库搬箱，没有到过二楼。",
    },
    {
      id: "fact_alibi_chen",
      type: "alibi",
      statement: "二十点三十分至二十一点三十五分，陈默本人连续身处城南诊所直播。",
    },
    {
      id: "fact_relationship_shen",
      type: "relationship",
      statement: "沈岚与父亲因遗产和藏品归属发生过激烈争吵。",
    },
    {
      id: "fact_context_zhao_fired",
      type: "context",
      statement: "赵衡因私自出售藏品信息被顾明远辞退。",
    },
    {
      id: "fact_sedative_source",
      type: "context",
      statement: "陈默曾为顾明远开具与茶中成分相同的镇静剂。",
    },
    {
      id: "fact_housekeeper_sighting",
      type: "opportunity",
      statement: "罗芳在案发前看见李闻舟独自把茶送往二楼。",
    },
  ],
  timeline: [
    {
      id: "event_prepare_tea",
      timestamp: "2026-08-30T20:38:00+08:00",
      sceneId: "scene_kitchen",
      characterIds: ["character_li_wenzhou", "character_luo_fang"],
      factIds: ["fact_housekeeper_sighting", "fact_method_sedative_bookend"],
      description: "李闻舟避开罗芳的视线，在茶中加入镇静剂后端走茶盘。",
    },
    {
      id: "event_enter_study",
      timestamp: "2026-08-30T21:06:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_li_wenzhou", "character_gu_mingyuan"],
      factIds: ["fact_opportunity_stolen_card"],
      description: "李闻舟使用备用门卡进入书房。",
    },
    {
      id: "event_murder",
      timestamp: "2026-08-30T21:10:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_li_wenzhou", "character_gu_mingyuan"],
      factIds: ["fact_method_sedative_bookend", "fact_time_of_death"],
      description: "药效发作后，李闻舟用黄铜书挡袭击顾明远。",
    },
    {
      id: "event_stage_scene",
      timestamp: "2026-08-30T21:16:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_li_wenzhou"],
      factIds: ["fact_opportunity_stolen_card"],
      description: "李闻舟擦拭书挡并删除部分门禁日志，试图制造密室假象。",
    },
    {
      id: "event_body_found",
      timestamp: "2026-08-30T21:32:00+08:00",
      sceneId: "scene_study",
      characterIds: ["character_luo_fang", "character_gu_mingyuan"],
      factIds: ["fact_time_of_death"],
      description: "罗芳送水时发现顾明远倒在书桌旁。",
    },
  ],
  claims: [
    {
      id: "claim_li_alibi",
      speakerId: "character_li_wenzhou",
      kind: "lie",
      statement: "八点半以后我一直在客房打电话，从未上过二楼。",
      factIds: ["fact_opportunity_stolen_card", "fact_housekeeper_sighting"],
    },
    {
      id: "claim_shen_alibi",
      speakerId: "character_shen_lan",
      kind: "truth",
      statement: "八点半到九点三十五分，我一直在西侧附楼修复室处理油画；调阅恒温记录时能一并取得固定机位的原始录像。",
      factIds: ["fact_alibi_shen"],
    },
    {
      id: "claim_zhao_alibi",
      speakerId: "character_zhao_heng",
      kind: "truth",
      statement: "八点半到九点三十五分，我在一楼和地下仓库之间搬箱子；货梯日志能和装卸区、轿厢、仓库的连续录像核对。",
      factIds: ["fact_alibi_zhao"],
    },
    {
      id: "claim_chen_alibi",
      speakerId: "character_chen_mo",
      kind: "truth",
      statement: "八点半到九点三十五分，我一直在城南诊所直播；平台保留了原始全景录像和实时观众提问。",
      factIds: ["fact_alibi_chen"],
    },
    {
      id: "claim_luo_tea",
      speakerId: "character_luo_fang",
      kind: "truth",
      statement: "我看见李闻舟说要替我送茶，然后一个人端着茶盘上楼。",
      factIds: ["fact_housekeeper_sighting"],
    },
    {
      id: "claim_han_logs",
      speakerId: "character_han_zhuo",
      kind: "truth",
      statement: "门禁记录被人为删除过，但底层备份可以恢复。",
      factIds: ["fact_deleted_security_log"],
    },
  ],
  evidence: [
    {
      id: "evidence_broken_watch",
      name: "停在九点十分的腕表与时间勘验记录",
      description: "检查腕表时一并取得对应物证编号的时间勘验原件：罗芳在首次现场笔录中记载，20:35她亲眼看着顾明远正常走入书房并与他交谈；21:32的原始报警录音及同期急救检查记录确认他已死亡。尸检附页确认损伤立即致命，不存在先前受伤后延迟死亡的情形。致命袭击因此限于20:35—21:32；腕表停在21:10只能佐证，不能单独定时。配茶经过仍须另行询问。",
      kind: "physical",
      supportsFactIds: ["fact_time_of_death"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "inspect",
        sceneId: "scene_study",
        objectId: "object_broken_watch",
        actionAliases: ["检查腕表", "查看表盘"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_teacup_residue",
      name: "茶杯中的镇静剂残留",
      description: "按罗芳已交付的洗杯、沏茶经过取样后，检验科交付茶水、血样及对照样本的原始报告：茶与死者生前吸收的成分相同，剂量足以造成明显迟钝，但不足以造成死亡或延迟致死。罗芳20:35洗杯后留下的末次冲洗水、刚开启的水和同批茶样均未检出该药，因此投放只能发生在20:35配茶开始后、致命袭击前。附存的处方原件载明陈默曾为顾明远开过同类药；处方只证明来源线索，不证明谁投药。此项尚不能确定致命凶器。",
      kind: "forensic",
      supportsFactIds: ["fact_sedative_in_tea", "fact_sedative_source"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "analyze",
        sceneId: "scene_study",
        objectId: "object_teacup",
        actionAliases: ["化验茶水", "检查杯底沉淀"],
        prerequisiteEvidenceIds: ["evidence_housekeeper_testimony"],
      },
    },
    {
      id: "evidence_brass_bookend",
      name: "被擦拭的黄铜书挡",
      description: "书挡检验原件显示，受害者创口内的黄铜碎屑可与书挡新缺角断面拼合，缝隙残留其血液与皮屑；尸检确认这次打击立即致命。结合已取得的茶水、血样报告，可确定先摄入非致死镇静剂、再遭黄铜书挡致命打击。另有与李闻舟西装袖口同类的纤维，但纤维只能提示接触，不能独自证明接触者或接触时间。",
      kind: "forensic",
      supportsFactIds: ["fact_method_sedative_bookend"],
      contradictsClaimIds: [],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "inspect",
        sceneId: "scene_study",
        objectId: "object_bookcase",
        actionAliases: ["检查黄铜书挡", "寻找擦拭痕迹"],
        prerequisiteEvidenceIds: ["evidence_teacup_residue"],
      },
    },
    {
      id: "evidence_transfer_ledger",
      name: "异常转账账簿",
      description: "账簿附银行转账回执与开户材料，显示基金会多笔未经授权的资金最终流入李闻舟控制的空壳账户。账簿本身未记载顾明远准备如何处置。",
      kind: "document",
      supportsFactIds: ["fact_fund_diversion"],
      contradictsClaimIds: [],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "search",
        sceneId: "scene_study",
        objectId: "object_desk",
        actionAliases: ["翻找书桌抽屉", "检查账簿"],
        prerequisiteEvidenceIds: [],
      },
    },
    {
      id: "evidence_torn_audit_memo",
      name: "被撕毁的审计备忘录",
      description: "拼合的备忘录逐项引用已取得账簿中的异常转账号，写明顾明远将在次日上午向警方提交李闻舟挪用资金的证据；页边留有李闻舟当晚签收后请求暂缓报警的答复。与账簿、银行附件合读，可确认挪用事实以及李闻舟已经知道的迫近追责。备忘录还夹着顾明远授权调阅安防备份的凭条，可据此进入安防室联系韩卓。",
      kind: "document",
      supportsFactIds: ["fact_motive_embezzlement"],
      contradictsClaimIds: [],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "inspect",
        sceneId: "scene_study",
        objectId: "object_desk",
        actionAliases: ["检查碎纸篓", "拼合备忘录"],
        prerequisiteEvidenceIds: ["evidence_transfer_ledger"],
      },
    },
    {
      id: "evidence_paint_curing_record",
      name: "修复室恒温记录与连续原片",
      description: "修复室档案终端已导出恒温记录及对应固定机位原片。20:30—21:35的连续全景画面能清楚辨认沈岚本人，始终显示她在顾宅西侧附楼修复台旁处理油画，人物没有离开画面；门窗和工作台位置可与场地档案核对，设备时钟与录像同源校时。全段未见剪接或缺帧，覆盖已核定的20:35配茶起点至21:32死亡上界，既排除她投放茶中药物，也排除她实施致命打击；双重认证仅用来对照操作记录。",
      kind: "digital",
      supportsFactIds: ["fact_alibi_shen"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: ["character_shen_lan"],
      critical: true,
      discovery: {
        method: "query",
        actionAliases: ["查询修复室记录", "核实沈岚的不在场证明"],
        prerequisiteEvidenceIds: ["evidence_broken_watch", "evidence_teacup_residue"],
      },
    },
    {
      id: "evidence_elevator_log",
      name: "货梯运行日志与沿途原片",
      description: "安防终端按原备份编号导出了20:30—21:35的货梯日志和一楼装卸区、轿厢、地下仓库录像。相邻机位有重叠视野，连续衔接的原片清楚显示赵衡本人始终在这些区域搬箱；每次换镜仍可见其面部与动作，人物没有画外空档，未到二楼。原片时钟与门禁同源校时，全段未见剪接或缺帧，覆盖已核定的20:35配茶起点至21:32死亡上界。门卡记录只作交叉比对，排除依据是连续本人画面。",
      kind: "digital",
      supportsFactIds: ["fact_alibi_zhao"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: ["character_zhao_heng"],
      critical: true,
      discovery: {
        method: "query",
        sceneId: "scene_security_room",
        objectId: "object_security_terminal",
        actionAliases: ["查询货梯日志", "核实赵衡的门卡"],
        prerequisiteEvidenceIds: ["evidence_torn_audit_memo", "evidence_broken_watch", "evidence_teacup_residue"],
      },
    },
    {
      id: "evidence_livestream_record",
      name: "陈默交付的直播原片与互动记录",
      description: "陈默已交付平台后台回放链接和原始互动记录，调查终端当场从平台调取了20:30—21:35完整原片。固定全景机位清楚显示陈默本人始终坐在城南诊所诊室内，脸部和身体持续在画面中；诊室陈设与平台当日场地登记照一致，实时观众问题与他的即时回答逐条对应。平台服务器时间连续，全段未见剪接、缺帧或人物离开画面，覆盖已核定的20:35配茶起点至21:32死亡上界。此项证明的是本人在诊所的连续位置。",
      kind: "digital",
      supportsFactIds: ["fact_alibi_chen"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: ["character_chen_mo"],
      critical: true,
      discovery: {
        method: "interview",
        characterId: "character_chen_mo",
        actionAliases: ["询问陈默案发时在哪里", "追问医学直播", "核实陈默的不在场证明"],
        dialogueAliases: [
          "案发时你在哪里",
          "你当晚一直在诊所吗",
          "医学直播能证明你的不在场吗",
        ],
        dialogueUtterance:
          "我已经把平台后台的回放链接和原始互动记录交给你了。请看终端刚从平台调出的20:30到21:35完整原片：我本人一直在城南诊所诊室的全景画面里，实时问题和我的即时回答也都在。",
        prerequisiteEvidenceIds: ["evidence_broken_watch", "evidence_teacup_residue"],
      },
    },
    {
      id: "evidence_smart_lock_log",
      name: "恢复的书房门禁日志",
      description: "从离线终端只追加的底层备份恢复出原日志：21:06，卡号与顾明远当日报失单一致的备用门卡打开书房；这条记录在21:16被人为删除。日志只记卡号、不记持卡人，尚不能据此认定李闻舟或反驳他的说法。备份索引同时给出相邻走廊录像的文件编号，可继续调取画面。",
      kind: "digital",
      supportsFactIds: ["fact_spare_card_entry", "fact_deleted_security_log"],
      contradictsClaimIds: [],
      implicatesCharacterIds: [],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "analyze",
        sceneId: "scene_security_room",
        objectId: "object_security_terminal",
        actionAliases: ["恢复门禁日志", "检查备用门卡记录"],
        prerequisiteEvidenceIds: ["evidence_torn_audit_memo"],
      },
    },
    {
      id: "evidence_camera_reflection",
      name: "监控玻璃中的倒影",
      description: "依门禁备份索引导出的走廊录像原片，在玻璃倒影中清楚拍到李闻舟的脸；连续画面从21:05他走上二楼，跟到21:06他亲手刷卡并跨入书房，全程没有换人或画外空档。录像与已恢复门禁日志使用同一校时源，刷卡动作对应的唯一开门记录正是报失备用卡。两份材料合起来才确认李闻舟持该卡入室，并推翻他八点半以后从未上楼的说法。",
      kind: "digital",
      supportsFactIds: ["fact_opportunity_stolen_card"],
      contradictsClaimIds: ["claim_li_alibi"],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "analyze",
        sceneId: "scene_security_room",
        objectId: "object_security_terminal",
        actionAliases: ["逐帧查看监控", "放大玻璃倒影"],
        prerequisiteEvidenceIds: ["evidence_smart_lock_log"],
      },
    },
    {
      id: "evidence_housekeeper_testimony",
      name: "罗芳关于茶盘的证词",
      description: "罗芳交代：20:35她洗净茶杯，20:36用刚开启的水和茶沏茶；20:38李闻舟主动接过茶盘，独自前往二楼。她随后送毛巾上楼，20:40看见顾明远在书房门口接过杯子喝茶。她没有看见投药，也未一直看守送达后的茶杯。水盆中的末次洗杯水和剩余水、茶仍可按她指认的位置分别取样化验。证词直接证明送茶经过，不单独证明药物或致命袭击。",
      kind: "testimony",
      supportsFactIds: ["fact_housekeeper_sighting"],
      contradictsClaimIds: ["claim_li_alibi"],
      implicatesCharacterIds: ["character_li_wenzhou"],
      excludesCharacterIds: [],
      critical: true,
      discovery: {
        method: "interview",
        characterId: "character_luo_fang",
        actionAliases: ["询问罗芳谁送了茶", "追问茶盘经过"],
        dialogueAliases: [
          "谁把茶送进书房",
          "茶盘后来是谁拿走的",
          "你看到谁去二楼了吗",
        ],
        dialogueUtterance:
          "20:35我洗净杯子，20:36新开了水和茶沏茶。20:38李闻舟主动接过茶盘，独自去了二楼；我随后送毛巾上楼，20:40看见顾先生在书房门口接杯喝茶。我没看到有人投药，也没一直看着送达后的杯子。水盆里最后一遍洗杯水和剩下的水、茶还在，可以分别取样。",
        prerequisiteEvidenceIds: [],
      },
    },
  ],
  unlockRules: [
    {
      id: "unlock_security_room",
      targetType: "scene",
      targetId: "scene_security_room",
      allEvidenceIds: ["evidence_torn_audit_memo"],
      anyEvidenceIds: [],
    },
    {
      id: "unlock_han_zhuo",
      targetType: "character",
      targetId: "character_han_zhuo",
      allEvidenceIds: ["evidence_torn_audit_memo"],
      anyEvidenceIds: [],
    },
  ],
  hintChains: [
    {
      id: "hint_motive",
      targetFactId: "fact_motive_embezzlement",
      hints: [
        "顾明远最近似乎准备采取一项正式行动。",
        "书桌附近可能留有与财务有关的材料。",
        "检查抽屉账簿和碎纸篓中的审计备忘录。",
      ],
    },
    {
      id: "hint_method",
      targetFactId: "fact_method_sedative_bookend",
      hints: [
        "受害者遇袭前的状态可能并不正常。",
        "茶杯和被擦拭过的摆件值得分别检查。",
        "化验冷茶，并检查书柜上的黄铜书挡。",
      ],
    },
    {
      id: "hint_opportunity",
      targetFactId: "fact_opportunity_stolen_card",
      hints: [
        "没有破门痕迹，不等于没人开过门。",
        "审计备忘录会引出一个新的调查地点。",
        "找到备忘录后前往安防室恢复门禁和监控记录。",
      ],
    },
  ],
  solution: {
    culpritId: "character_li_wenzhou",
    motiveFactId: "fact_motive_embezzlement",
    methodFactId: "fact_method_sedative_bookend",
    requiredEvidenceIds: [
      "evidence_broken_watch",
      "evidence_teacup_residue",
      "evidence_brass_bookend",
      "evidence_transfer_ledger",
      "evidence_torn_audit_memo",
      "evidence_paint_curing_record",
      "evidence_elevator_log",
      "evidence_livestream_record",
      "evidence_smart_lock_log",
      "evidence_camera_reflection",
      "evidence_housekeeper_testimony",
    ],
    requiredTimelineEventIds: [
      "event_prepare_tea",
      "event_enter_study",
      "event_murder",
    ],
  },
});
